export const WORDS_LOAD_START = 'WORDS_LOAD_START';
export const WORDS_LOAD_SUCCESS = 'WORDS_LOAD_SUCCESS';
export const WORD_REMOVE_SUCCESS = 'WORD_REMOVE_SUCCESS';
export const WORD_UPDATE_SUCCESS = 'WORD_UPDATE_SUCCESS';
export const WORD_ADD_SUCCESS = 'WORD_ADD_SUCCESS';

export const WORD_EDIT_START = 'WORD_EDIT_START';
export const WORD_EDIT_CANCEL = 'WORD_EDIT_CANCEL';

export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_OUT_SUCCESS = 'USER_SIGN_OUT_SUCCESS';
