export const WORDS_LOAD_START = 'WORDS_LOAD_START';
export const WORDS_LOAD_SUCCESS = 'WORDS_LOAD_SUCCESS';
export const WORD_REMOVE_SUCCESS = 'WORD_REMOVE_SUCCESS';
export const WORD_UPDATE_SUCCESS = 'WORD_UPDATE_SUCCESS';
export const WORD_ADD_SUCCESS = 'WORD_ADD_SUCCESS';

export const WORD_EDIT_START = 'WORD_EDIT_START';
export const WORD_EDIT_CANCEL = 'WORD_EDIT_CANCEL';

export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_OUT_SUCCESS = 'USER_SIGN_OUT_SUCCESS';

export const GAME_LOAD_WORDS_SUCCESS = 'GAME_LOAD_WORDS_SUCCESS';
export const GAME_START = 'GAME_START';
export const GAME_END = 'GAME_END';
export const GAME_NEXT_WORD = 'GAME_NEXT_WORD';
export const GAME_SET_CORRECT_ANSWER = 'GAME_SET_CORRECT_ANSWER';
export const GAME_SET_WRONG_ANSWER = 'GAME_SET_WRONG_ANSWER';